### PR TITLE
Render context into the popver

### LINKED ISSUE #66: Popover does not keep the context of the child
The popover prop body does not keep the context of its children, which makes it difficult to use when the children rely on props with context..

### PR DESCRIPTION
**Pull request by clayne11**
When rendering the popover, we need to keep the context.

Render using ReactDOM.renderSubtreeIntoContainer rather than ReactDOM.render.

Fixes #66

### CODE REVIEW

**Comment by caseyg1204** [comment]
this resolves the issue I was having. thanks

**Comment by khankuan** [comment]
+1

**Comment by tikotzky** [comment]
I just bumped into this issue as well...
Anything holding the PR back from being merged (other that rebasing against current master)?

**Comment by amok** [comment]
+1

**Comment by Justkant** [comment]
I'd like to see this merge

**Comment by maxdow** [comment]
works like a charm. What about merging ?

**Comment by jasonkuhrt** [comment]
Thanks for the contribution and efforts @clayne11. I fixed this is #92.

**Pull request closed without merging**
